### ISSUE TITLE
Raw doesn't work for unknown tags

### ISSUE THREAD

**Issue by gjtorikian** [docs/liquid#40] opened 2015-10-14 18:05 UTC
Suppose you have some content like this:

```
{% raw %}
{% example_tag %}
{% endraw %}
```

`liquid-node` complains that the `example_tag` tag does not exist. Ideally, the `raw` tags should completely ignore the content within it, not just tags it recognizes.

I can try to provide a PR to fix this if it's desired.

**Comment by sirlantis** [comment] 2015-10-14 22:06
@gjtorikian I just added a test to verify but I can't reproduce that issue you are talking of - maybe your version is out of date? PRs always welcome. :)

**Comment by JasonEtco** [comment] 2020-10-01 15:19
I think this is fixed, I can't seem to reproduce it either - and we're 5 years in 😂 closing!

**Closed by JasonEtco** 2020-10-01 15:19 UTC
