### ISSUE TITLE
Any way of passing parameters to include?

### ISSUE THREAD

**Issue by pburrows** [docs/liquid#81] opened 2019-08-06 12:49 UTC
I see issue #37 where @sirlantis mentions that the workaround to passing parameters is to use assign like this:

```
{% assign snippet_variable = 'this is it' %}
{% assign snippet_variable_two = 'this is also it' %}
{% include 'snippet' %}
```

And I see issue #42 where @divillysausages wrote code that implements passing parameters to an include as standard liquid is supposed to.

But I do not see where any of those options currently work. Using `assign` does not seem to do anything, and Mr. Sausages code seems to not have been included in the full source.

Is there currently a way that works to pass parameters to an include file from another file?

**Comment by JasonEtco** [comment] 2020-10-01 15:20
Closing as a duplicate of #37 - notably, #114 is open which would add an alternative tag for this use-case.

**Closed by JasonEtco** 2020-10-01 15:20 UTC
